conda-forge/pyiron_atomistics-feedstock

- recipe/meta.yaml
> Manual update to 0.2.3

- recipe/meta.yaml
> Remove optional pymatgen dependency

- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- LICENSE.txt
- README.md
- recipe/meta.yaml
> Manual update to 0.2.4

- recipe/meta.yaml
> Update HDF5 requirement for compatibility with tensor flow

- recipe/meta.yaml
> Require latest pyiron_data

- recipe/meta.yaml
> Update pyiron-data to 0.0.9 

- recipe/meta.yaml
> Require pyiron-data 0.0.10

- recipe/meta.yaml
> Manual update to 0.2.5 

- recipe/meta.yaml
> Manual update to 0.2.6

- recipe/meta.yaml
> Manual update to 0.2.8

- recipe/meta.yaml
> Remove molmod from dependencies

- recipe/meta.yaml
> Manual update to 0.2.9 

- .scripts/run_docker_build.sh
- build-locally.py
- recipe/meta.yaml
> Manual update to 0.2.11

- recipe/meta.yaml
> Manual Update to 0.2.12

- recipe/meta.yaml
This is no longer required once https://github.com/pyiron/pyiron_atomistics/pull/345 is merged.
Checklist
> Reduce six dependency for tensor flow

- README.md
- recipe/meta.yaml
> Manual update to 0.2.30

- .ci_support/linux_64_.yaml
- recipe/meta.yaml
> Numba compatibility

- recipe/meta.yaml
> Update to 0.2.31

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- recipe/meta.yaml
> Python 3.7 compatibility 

- recipe/meta.yaml
- recipe/scipy.patch
> Fix scipy bug and dependencies

- recipe/meta.yaml
> Add pint dependency

- recipe/meta.yaml
> Update to pyiron-data 0.0.18

- recipe/meta.yaml
> Update to version 0.2.44

- recipe/import.patch
- recipe/meta.yaml
> Patch pyiron_base imports

- recipe/meta.yaml
> pyiron_atomistics-0.2.58

- recipe/meta.yaml
> Be careful with the latest phony version

- recipe/meta.yaml
> Update to 0.2.62

- recipe/meta.yaml
> Update to 0.2.63

- recipe/meta.yaml
> Update to 0.2.65

- recipe/meta.yaml
> Update to pyiron_atomistics-0.2.67

- recipe/conda_build_config.yaml
- recipe/meta.yaml
> add possibility for dev release

- .ci_support/linux_64_.yaml
- recipe/meta.yaml
> Rerender to fix dev release

- recipe/meta.yaml
> Update to version 0.4.0

- .gitignore
- recipe/meta.yaml
> Bump to 0.4.1

- recipe/meta.yaml
> Update to 0.4.4

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_.yaml
- .scripts/build_steps.sh
- build-locally.py
- recipe/meta.yaml
> Update to 0.4.18

- recipe/meta.yaml
> Update to 0.5.0

- recipe/meta.yaml
> Limit maximum Python version

- recipe/elastic.patch
- recipe/meta.yaml
> Patch elastic matrix bug

- recipe/meta.yaml
> Update pyiron_atomistics to 0.6.3

- recipe/meta.yaml
> Update to 0.6.6

- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
> Update to 0.6.7

- recipe/meta.yaml
> Update to 0.6.9

- .scripts/build_steps.sh
- azure-pipelines.yml
- recipe/meta.yaml
> Update to 0.6.14

- recipe/meta.yaml
> Update to 0.6.21

- .scripts/run_docker_build.sh
- build-locally.py
- recipe/meta.yaml
> Update pyiron_atomistics to 0.7.3

- recipe/meta.yaml
> Update pyiron_atomistics to 0.7.5

- recipe/meta.yaml
> Update to 0.7.7

- build-locally.py
- recipe/meta.yaml
> Update to 0.7.9

- recipe/meta.yaml
> Update to 0.7.10

- .scripts/build_steps.sh
- conda-forge.yml
- pixi.toml
- recipe/recipe.yaml
> Convert feedstock to v1 recipe format

- recipe/recipe.yaml
> Update to 0.7.13

- recipe/recipe.yaml
> Update to 0.7.14

- pixi.toml
- recipe/recipe.yaml
> update to 0.7.17

- recipe/recipe.yaml
> Fix pylammpsmpi version restriction
